version: 2
jobs:
  build:
    machine: true    
    steps:
      - checkout

      - run:
          name: install and execute
          command: |
            bundle install
            bundle exec ensure_arduino_installation.rb
            # manually install the external libraries
            mkdir -p ~/Arduino/libraries
            mv ~/project/externals/* ~/Arduino/libraries/
            git clone https://github.com/balp/arduino-mock.git ~/arduino-mock
            mv ~/arduino-mock/* ~/Arduino/libraries/
            # now run CI
            bundle exec arduino_ci_remote.rb
